import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { OpenpanelProvider } from '@openpanel/nextjs'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const profileId = '736d86b0-4a77-43d8-ae79-6ed83187fd85'
  return (
    <html lang="en">
      <OpenpanelProvider
        clientId="188093bf-41d1-4982-a2fb-15f761109f51"
        trackScreenViews
        trackAttributes
        trackOutgoingLinks
        // optional
        profileId={profileId}
      />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
